ROR_doc/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users
  post '/auth/login', to: 'authentication#login'

  resources :products
  # root "products#index"

  resources :branches

  resources :branches do
    member do
      patch :restore
    end
  end
  
  Rails.application.routes.draw do
    namespace :api do
      namespace :v1 do
        resources :credit_cards do
         member do
          patch :restore
          patch :discard
         end
        end
      end 
    end
  end

  Rails.application.routes.draw do
    namespace :api do
      namespace :v1 do
        resources :customers, params: :customer_id
        resources :credit_cards, params: :credit_card_id
        resources :account_transactions, params: :transaction_id
        resources :branches, params: :branch_id
        resources :rewards, params: :reward_id
        resources :user_cards, params: :user_card_id
      end
    end
  end

end

ROR_doc/app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :quantity, presence: true
end

ROR_doc/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end
  



  private
    def product_params
      params.require(:product).permit(:name, :quantity)
    end



end

ROR_doc/app/helpers/products_helper.rb
module ProductsHelper
end

ROR_doc/app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% product.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :quantity %><br>
      <%= form.text_area :quantity %><br>
      <% product.errors.full_messages_for(:quantity).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

ROR_doc/app/views/products/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", product: @product %>

ROR_doc/app/views/products/index.html.erb
<h1>Products</h1>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.name, product %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_product_path %>

ROR_doc/app/views/products/new.html.erb
<h1> New Product </h1>

<%= render "form", product: @product %>

ROR_doc/app/views/products/show.html.erb
<h1> <%= @product.name %> <h1>
<h2> <%= @product.quantity %> <h2>


<%= link_to "Back", products_path %>
<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Destroy", product_path(@product), data:{
    turbo_method: :delete,
    turbo_confirm: "Are you Sure?"
} %>